server:
  port: 8092
  servlet:
    contextPath: /ems
  ssl:
    enabled: false
    key-store: ../certificates/ssl.jks
    key-store-password: pathbreaker
    key-alias: pbt
    key-store-type: JKS
spring:
  aop:
    proxy-target-class: true
  main:
    allow-circular-references: true
    # Multipart configuration
    servlet:
      multipart:
        enabled: true
        max-file-size: 2GB
        max-request-size: 2GB
  thymeleaf:
    cache: false
  security:
    basic:
      enabled: false
fixed:
  otp: 123456
es:
  esHost: localhost
  esPort: 9200
springdoc:
  swagger-ui:
    tagsSorter: alpha
    path: /swagger-ui
  api-docs:
    resolve-schema-properties: true
    path: /api-docs
file:
  upload:
    path: '/var/www/ems/assets/img/'
